---

- name: "install python for Ansible."
  become: true
  yum:
    name: python3
    state: latest

- name: "upgrade packages."
  become: true
  yum:
    name: '*'
    state: latest 

- name: "install dependencies."
  become: true
  yum:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present