---
- name: 'update and upgrade packages.'
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: extract artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start