---
- name: 'update and upgrade packages.'
  become: true
  apt:
    upgrade: yes
    update_cache: yes   

- name: extract artifact
  become: true
  unarchive:
    src: ~/
    dest: ~/

- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    sudo pm2 start npm -- start